#!/bin/bash

menu (){
	clear
	echo "1-Comprimir"
	echo "2-Descomprimir"
	echo "0-Exit"
	read opcion
}

comprimir (){
	echo "Sichero que quieres comprimir"
	read fichero
	echo "Directorio del fichero"
	read directorio

        cd $directorio 2>>/tmp/errores.txt

if [ $fichero ]
	then
	tar -czvf $fichero.tgz $fichero
else
echo "El $fichero no se puede comprimir"
fi
}

descomprimir (){ 
        echo "Fichero que quieres descomprimir"
	read fichero
	echo "Directorio donde se encuentra el fichero"
	read directorio

       cd $directorio 2>>/tmp/errores.txt

if [ $fichero ]
	then
	tar -xzvf $fichero
else 
echo "El $fichero no se puede descomprimir"
fi
}

opciones (){
case $opcion in
	1)comprimir;;
	2)descomprimir;;
	0)exit 0;;
esac
}

while true
do

 menu
	if [ $opcion -le 2 ] && [ $opcion -ge 0 ] 
	then
	opciones
	else  echo "Elige una opcion de las anteriores"
	fi
read -p "Pulse para continuar"
done
